use crate::components::{Displayed, Named, Positioned};
use crate::ecs::{AwareOfComponent, HasComponent};

// ECS: components' types are parameters when defining new entity
pub struct Player {
    named: Named,
    positioned: Positioned,
    displayed: Displayed,
}

impl Player {
    pub fn new(named: Named, positioned: Positioned, displayed: Displayed) -> Self {
        Self { named, positioned, displayed }
    }
}

// ECS: easily autogenerated code
impl HasComponent<Named> for Player {
    fn get_component_raw(&self) -> &Named {
        &self.named
    }
}

impl HasComponent<Positioned> for Player {
    fn get_component_raw(&self) -> &Positioned {
        &self.positioned
    }
}

impl HasComponent<Displayed> for Player {
    fn get_component_raw(&self) -> &Displayed {
        &self.displayed
    }
}

// ECS: still easily autogenerated
impl AwareOfComponent<Named> for Player {
    fn try_get_component_raw(&self) -> Option<&Named> {
        Some(&self.named)
    }
}

impl AwareOfComponent<Positioned> for Player {
    fn try_get_component_raw(&self) -> Option<&Positioned> {
        Some(&self.positioned)
    }
}

impl AwareOfComponent<Displayed> for Player {
    fn try_get_component_raw(&self) -> Option<&Displayed> {
        Some(&self.displayed)
    }
}