[package]
name = "ecs_macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "ecs_macros"
path = "src/lib.rs"
proc_macro = true

[dependencies]
quote = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
proc-macro2 = "*"
